'use client';
import { useState } from 'react';

export default function PokerTracker() {
  // Constants
  const BUY_IN_AMOUNT = 20;

  // State
  const [roster, setRoster] = useState(['KT', 'Chaitanya', 'Prasad', 'Guru', 'Arveen', 'Mallela']); 
  const [sessionPlayers, setSessionPlayers] = useState([]);
  const [isSessionActive, setIsSessionActive] = useState(false);
  const [showRoster, setShowRoster] = useState(false);
  const [newPlayerName, setNewPlayerName] = useState('');

  // Functions
  const addToSession = (name) => {
    if (!sessionPlayers.find(p => p.name === name)) {
      setSessionPlayers([...sessionPlayers, { name: name, buyins: 1, cashOut: 0 }]);
    }
    setShowRoster(false);
  };

  const addNewToRoster = () => {
    if (newPlayerName.trim()) {
      setRoster([...roster, newPlayerName.trim()]);
      addToSession(newPlayerName.trim());
      setNewPlayerName('');
    }
  };

  const updateBuyins = (index, delta) => {
    const updated = [...sessionPlayers];
    updated[index].buyins = Math.max(1, updated[index].buyins + delta);
    setSessionPlayers(updated);
  };

  const handleCashOut = (index, val) => {
    const updated = [...sessionPlayers];
    updated[index].cashOut = Number(val);
    setSessionPlayers(updated);
  };

  const calculateNet = (p) => p.cashOut - (p.buyins * BUY_IN_AMOUNT);

  const shareToWhatsApp = () => {
    const summary = sessionPlayers.map(p => {
      const net = calculateNet(p);
      return `${p.name}: ${net >= 0 ? '+' : ''}$${net}`;
    }).join('\n');
    const text = `🃏 *ChillBoyz Poker Report* 🃏\n\n${summary}\n\n_Generated by ChillBoyz AI_`;
    window.open(`https://wa.me/?text=${encodeURIComponent(text)}`, '_blank');
  };

  // Styles (Inline for Build Safety)
  const styles = {
    container: { backgroundColor: '#020617', minHeight: '100vh', color: 'white', padding: '20px', fontFamily: 'sans-serif' },
    card: { backgroundColor: '#0f172a', padding: '15px', borderRadius: '15px', border: '1px solid #1e293b', marginBottom: '15px' },
    buttonPrimary: { backgroundColor: '#ca8a04', padding: '15px 30px', borderRadius: '50px', fontWeight: 'bold', border: 'none', color: 'white', cursor: 'pointer' },
    buttonSecondary: { backgroundColor: '#1e293b', padding: '10px', borderRadius: '10px', border: '1px solid #334155', color: 'white', width: '100%' },
    input: { width: '100%', padding: '10px', borderRadius: '8px', background: '#020617', border: '1px solid #334155', color: 'white', marginTop: '10px', outline: 'none' },
    badge: { fontSize: '10px', fontWeight: 'bold', color: '#eab308', border: '1px solid #eab308', padding: '2px 8px', borderRadius: '20px', display: 'inline-block', marginBottom: '10px' }
  };

  return (
    <div style={styles.container}>
      <header style={{ textAlign: 'center', marginBottom: '30px' }}>
        <h1 style={{ color: '#eab308', fontSize: '26px', fontWeight: '900', letterSpacing: '-1px' }}>CHILLBOYZ POKER</h1>
        <div style={styles.badge}>UNSETTLED SESSION</div>
      </header>

      {!isSessionActive ? (
        <div style={{ textAlign: 'center', marginTop: '100px' }}>
          <button onClick={() => {setIsSessionActive(true); setShowRoster(true);}} style={styles.buttonPrimary}>
            START NEW SESSION
          </button>
        </div>
      ) : (
        <div>
          {sessionPlayers.map((p, i) => (
            <div key={i} style={styles.card}>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                <span style={{ fontWeight: 'bold', fontSize: '18px' }}>{p.name}</span>
                <div style={{ display: 'flex', alignItems: 'center', gap: '12px', background: '#020617', padding: '5px', borderRadius: '10px' }}>
                  <button onClick={() => updateBuyins(i, -1)} style={{ background: 'none', border: 'none', color: 'white', fontSize: '20px' }}>-</button>
                  <span style={{ color: '#eab308', fontWeight: 'bold', minWidth: '40px', textAlign: 'center' }}>{p.buyins}</span>
                  <button onClick={() => updateBuyins(i, 1)} style={{ background: 'none', border: 'none', color: 'white', fontSize: '20px' }}>+</button>
                </div>
              </div>
              <input 
                type="number" 
                placeholder="Cash Out Amount" 
                style={styles.input} 
                onChange={(e) => handleCashOut(i, e.target.value)}
              />
              <div style={{ textAlign: 'right', marginTop: '10px', fontWeight: '900', fontSize: '20px', color: calculateNet(p) >= 0 ? '#4ade80' : '#f87171' }}>
                {calculateNet(p) >= 0 ? `+$${calculateNet(p)}` : `-$${Math.abs(calculateNet(p))}`}
              </div>
            </div>
          ))}

          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '10px', marginTop: '20px' }}>
            <button onClick={() => setShowRoster(true)} style={styles.buttonSecondary}>+ Add Player</button>
            <button onClick={shareToWhatsApp} style={{ ...styles.buttonSecondary, backgroundColor: '#15803d' }}>WhatsApp</button>
          </div>
          
          <button onClick={() => {if(confirm('End session?')) setIsSessionActive(false)}} style={{ ...styles.buttonSecondary, marginTop: '15px', color: '#f87171', borderColor: '#7f1d1d' }}>
            End Session (Unsettled)
          </button>
        </div>
      )}

      {/* Roster Bottom Sheet */}
      {showRoster && (
        <div style={{ position: 'fixed', bottom: 0, left: 0, right: 0, background: '#0f172a', padding: '25px', borderTopLeftRadius: '30px', borderTopRightRadius: '30px', borderTop: '2px solid #eab308', zIndex: 100 }}>
           <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '20px' }}>
             <h3 style={{ margin: 0 }}>Select Player</h3>
             <button onClick={() => setShowRoster(false)} style={{ background: 'none', border: 'none', color: '#94a3b8' }}>Close</button>
           </div>
           <div style={{ display: 'flex', flexWrap: 'wrap', gap: '10px', marginBottom: '20px' }}>
             {roster.map(r => (
               <button key={r} onClick={() => addToSession(r)} style={{ padding: '10px 15px', background: '#1e293b', border: 'none', color: 'white', borderRadius: '8px' }}>{r}</button>
             ))}
           </div>
           <div style={{ borderTop: '1px solid #1e293b', paddingTop: '15px' }}>
             <input 
               type="text" 
               placeholder="New Player Name" 
               value={newPlayerName}
               onChange={(e) => setNewPlayerName(e.target.value)}
               style={styles.input} 
             />
             <button onClick={addNewToRoster} style={{ ...styles.buttonPrimary, width: '100%', marginTop: '10px', padding: '10px' }}>Add & Select</button>
           </div>
        </div>
      )}
    </div>
  );
}
